name: Automatic Testing

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  test_and_build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install PyQt5 pyinstaller pytest psutil pytestqt
        run: |
          pip install PyQt5 pyinstaller pytest psutil pytest-qt

      - name: Run tests
        run: pytest test_TestComputerInfoApp.py -v

