name: Automatic Testing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Uruchamianie raz w tygodniu o północy w niedzielę
  workflow_dispatch:  # Uruchamianie ręcznie przez użytkownika

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run Unit Tests
        run: pytest Lista_2_Msz.py

      - name: Build EXE
        run: pyinstaller --onefile Lista_2_Msz.py

      - name: Run Application Tests
        run: python Lista_2_Msz.py || exit 0

