name: Automatyczne Budowanie

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Uruchamianie raz w tygodniu o północy w niedzielę
  workflow_dispatch:  # Uruchamianie ręcznie przez użytkownika

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install PyQt5 pyinstaller pytest

      - name: Build EXE
        run: pyinstaller --onefile Lista_2_Msz.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: exe-artifact
          path: dist/main
